build: false
environment:
    PYTHON: "C:\\Python27-x64"
    PYTHON_VERSION: "2.7.11"
    PYTHON_ARCH: "64"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "dlib/19.1.0"
    CONAN_USERNAME: "sunxfancy"
    CONAN_CHANNEL: "ci"
    CONAN_TOTAL_PAGES: 4
    CONAN_STABLE_BRANCH_PATTERN: "master"

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'
  - set PATH=%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan_package_tools # It install conan too
  - conan user sunxfancy # It creates the conan data directory

test_script:
  - C:\Python27-x64\python build.py
